upstream_services:
- name: stripe
  upstream_auth:
    bearer_token:
      token:

        plain_text: "${STRIPE_API_KEY}"

  openapi_service:
    address: "https://api.stripe.com"
    spec_url: "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.yaml"
