{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcpany.fullname" . }}-config
  labels:
    {{- include "mcpany.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | nindent 4 }}
{{- end }}
