# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcpany.serviceAccountName" . }}
  labels:
    {{- include "mcpany.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
