# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
        exclude: ^helm/
    -   id: detect-private-key
        exclude: ^tests/tls/
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: golangci-lint
        name: golangci-lint
        entry: ./build/env/bin/golangci-lint run --fix ./cmd/... ./pkg/... ./proto/... ./tests/... ./examples/...
        language: system
        types: [go]
        pass_filenames: false
    -   id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: ^vendor/
    -   id: helm-lint
        name: helm-lint
        entry: helm lint helm/mcpany
        language: system
        files: ^helm/
        pass_filenames: false
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
    -   id: markdownlint
        args: [--fix, --disable, MD013]
