# Copyright (C) 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
        exclude: ^helm/
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/golangci/golangci-lint
    rev: v2.6.0
    hooks:
    -   id: golangci-lint
        args: [--enable=gosec, ./...]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        types: [markdown]
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
    -   id: helmlint
-   repo: local
    hooks:
    -   id: shellcheck
        name: ShellCheck
        entry: shellcheck
        language: system
        types: [shell]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
    -   id: markdownlint
        args: [--fix, --disable, MD013]
-   repo: https://github.com/ansys/pre-commit-hooks
    rev: v0.5.2
    hooks:
    -   id: add-license-headers
        files: .
        types_or: [go, python, shell, yaml, proto, makefile]
        args:
        - --custom_copyright
        - "Author(s) of MCP Any"
        - --custom_license
        - "Apache-2.0"
        exclude: |
            (?x)^(
                 Makefile|
                 docker-compose.yml|
                 go.mod|
                 go.sum|
                 go.work.sum|
                .*\.pb\.go|
                vendor/.*|
                examples/.*|
                build/.*|
                helm/.*
            )$
