# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
        exclude: ^helm/
    -   id: detect-private-key
        exclude: ^tests/tls/
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/golangci/golangci-lint
    rev: v2.7.2
    hooks:
    -   id: golangci-lint
        args: [--fix, --allow-parallel-runners]
        pass_filenames: false
        exclude: ^build/
-   repo: local
    hooks:
    -   id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: ^vendor/
    -   id: helm-lint
        name: helm-lint
        entry: ./build/env/bin/helm lint helm/mcpany
        language: system
        files: ^helm/
        pass_filenames: false
-   repo: https://github.com/google/addlicense
    rev: v1.2.0
    hooks:
    -   id: addlicense
        args:
            - -c
            - "Author(s) of MCP Any"
            - -l
            - apache
            - -ignore
            - "build/**"
            - -ignore
            - "vendor/**"
            - -ignore
            - "**/*.pb.go"
            - -s=only
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
    -   id: markdownlint
        args: [--fix, --disable, MD013]
