# Copyright 2026 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

upstream_services:
  - name: "broken-command-service"
    command_line_service:
      command: "this-command-does-not-exist arg1"
