upstreamServices:
  - name: "stdio-echo"
    stdioService:
      command: "./examples/stdio/echo.sh"
      calls:
        - name: "echo"
          description: "Echo a message"
          parameterMappings:
            - inputParameterName: "message"
              targetParameterName: "message"
