# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

upstream_services:
  - name: "incoming-auth-service"
    authentication:
      api_key:
        param_name: "X-Auth"
        in: "HEADER"
        verification_value: "s3cret"
    http_service:
      address: "https://example.com"

  - name: "outgoing-auth-service"
    upstream_auth:
      basic_auth:
        username: "admin"
        password:
           plain_text: "password123"
    http_service:
      address: "https://example.com"
