# Copyright 2024 Author(s) of MCP Any
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

upstream_services:
- name: google_calendar
  http_service:
    address: "https://www.googleapis.com"
    upstream_authentication:
        api_key:
          header_name: "x-goog-api-key"
          api_key:
            plain_text: "${GOOGLE_API_KEY}"
    calls:
    - endpoint_path: "/calendar/v3/calendars/{{calendarId}}/events"
      schema:
        name: "list_events"
        input_schema:
          type: "object"
          properties:
            calendarId:
              type: "string"
              description: "The ID of the calendar to list events from."
        output_schema:
          type: "object"
          properties:
            kind:
              type: "string"
            etag:
              type: "string"
            summary:
              type: "string"
            updated:
              type: "string"
              format: "date-time"
            timeZone:
              type: "string"
            accessRole:
              type: "string"
            defaultReminders:
              type: "array"
              items: {}
            nextSyncToken:
              type: "string"
            items:
              type: "array"
              items:
                type: "object"
                properties:
                  kind:
                    type: "string"
                  etag:
                    type: "string"
                  id:
                    type: "string"
                  status:
                    type: "string"
                  htmlLink:
                    type: "string"
                  created:
                    type: "string"
                    format: "date-time"
                  updated:
                    type: "string"
                    format: "date-time"
                  summary:
                    type: "string"
                  creator:
                    type: "object"
                    properties:
                      email:
                        type: "string"
                  organizer:
                    type: "object"
                    properties:
                      email:
                        type: "string"
                      displayName:
                        type: "string"
                      self:
                        type: "boolean"
                  start:
                    type: "object"
                    properties:
                      date:
                        type: "string"
                        format: "date"
                  end:
                    type: "object"
                    properties:
                      date:
                        type: "string"
                        format: "date"
                  transparency:
                    type: "string"
                  iCalUID:
                    type: "string"
                  sequence:
                    type: "integer"
                  eventType:
                    type: "string"
      method: "HTTP_METHOD_GET"
