# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

upstream_services:
- name: github
  upstream_auth:
    bearer_token:
      token:

        plain_text: "${GITHUB_TOKEN}"

  openapi_service:
    address: "https://api.github.com"
    spec_url: "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml"
