upstream_services:
  - name: "git"
    command_line_service:
      command: "git"
      working_directory: "."
      tools:
        - name: "status"
          call_id: "status"
        - name: "log"
          call_id: "log"
        - name: "diff"
          call_id: "diff"
      calls:
        "status":
          args: ["status"]
        "log":
          args: ["log", "-n", "5"]
        "diff":
          args: ["diff", "HEAD~1", "HEAD"]
