# Copyright 2025 Author(s) of MCP Any
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

services:
  dev:
    network_mode: host
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.cache:/home/user/.cache
    working_dir: /workspace
    # Mount Go cache to speed up subsequent builds
    # Environment variables to force Go to use the mapped directory
    environment:
      - HOME=/home/user
      - GOCACHE=/home/user/.cache/go-build
      - GOMODCACHE=/home/user/.cache/go-mod
      - XDG_CACHE_HOME=/home/user/.cache
      - npm_config_cache=/home/user/.cache/npm
      - CI=true
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    user: "${UID:-1000}:${GID:-1000}"
