# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
        exclude: ^server/helm/
    -   id: detect-private-key
        exclude: ^server/tests/tls/
    -   id: end-of-file-fixer
        exclude: ^server/pkg/upstream/mcp/s1/manifest.json
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
        exclude: |
            (?x)^(
                vendor/|
                get_helm.sh
            )$
    -   id: helm-lint
        name: helm-lint
        entry: helm lint server/helm/mcpany
        language: system
        files: ^server/helm/
        pass_filenames: false
-   repo: https://github.com/google/addlicense
    rev: v1.2.0
    hooks:
    -   id: addlicense
        args:
            - -c
            - "Author(s) of MCP Any"
            - -l
            - apache
            - -ignore
            - "build/**"
            - -ignore
            - "vendor/**"
            - -ignore
            - "**/*.pb.go"
            - -s=only
