global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
- name: ip-info-service
  upstream_authentication:
    use_environment_variable: true
    bearer_token:
        token: "{{IPINFO_API_TOKEN}}"
  http_service:
    address: "https://ipinfo.io"
    calls:
    - schema:
        name: "get_time_by_ip"
        description: "Gets the current time for a given IP address."
      endpoint_path: "/{{ip}}/json"
      method: "HTTP_METHOD_GET"
      parameters:
      - schema:
          name: "ip"
          description: "The IP address to get the time for."
          is_required: true
          type: "STRING"
