# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
- name: greeter-service
  grpc_service:
    address: "localhost:50051"
    use_reflection: true
