# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

upstream_services:
  - name: "profiled-service"
    profiles:
      - name: "dev"
      - name: "staging"
    http_service:
      address: "https://example.com"
