# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

global_settings:
  bind_address: "0.0.0.0:8081"
upstream_services:
- name: echo-service
  websocket_service:
    address: "ws://localhost:8082/echo"
    calls:
    - schema:
        name: "echo"
        description: "Echoes a message back."
      parameters:
      - schema:
          name: "message"
          description: "The message to echo"
          is_required: true
          type: "STRING"
