# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mcpany'
    static_configs:
      - targets: ['mcpany-server:9090']
