# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

upstream_services:
  - name: "rate-limited-service"
    rate_limit:
      is_enabled: true
      requests_per_second: 50.0
      burst: 100
    http_service:
      address: "https://example.com"
