upstream_services:
  - name: miro
    upstream_auth:
      bearer_token:
        token:
          plain_text: "${MIRO_API_TOKEN}"
    http_service:
      address: "https://api.miro.com"
      tools:
        - name: "get_boards"
          call_id: "get_boards"
      calls:
        get_boards:
          endpoint_path: "/v2/boards"
          method: "HTTP_METHOD_GET"
          input_schema:
            type: "object"
            properties: {}
          output_schema:
            type: "object"
            properties:
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "string"
                    name:
                      type: "string"
                    description:
                      type: "string"
                    viewLink:
                      type: "string"
