global_settings:
  bind_address: "0.0.0.0:8080"
upstream_services:
  - name: "kubectl"
    command_line_service:
      command: "kubectl"
      calls:
        - schema:
            name: "get-pods"
            description: "Get pods in a namespace"
          args:
            - "get"
            - "pods"
            - "-n"
            - "{{ .namespace }}"
            - "-o"
            - "json"
          parameters:
            - schema:
                name: "namespace"
                description: "The namespace to get pods from"
                is_required: true
                type: "STRING"
        - schema:
            name: "get-deployments"
            description: "Get deployments in a namespace"
          args:
            - "get"
            - "deployments"
            - "-n"
            - "{{ .namespace }}"
            - "-o"
            - "json"
          parameters:
            - schema:
                name: "namespace"
                description: "The namespace to get deployments from"
                is_required: true
                type: "STRING"
