# Copyright 2025 Author(s) of MCP Any
# SPDX-License-Identifier: Apache-2.0

upstream_services:
  - name: "monitored-service"
    http_service:
      address: "https://example.com"
      tools:
        - name: "monitored-tool"
